### ISSUE TITLE
Grading Week 2

### ISSUE THREAD

**Issue by MathieuHoude** [EmmanuellaD/Rocket_Elevators_Controllers#1]
Good job overall on this week project. I'm glad to see that you started the ruby bonus, even tough it is incomplete.
I'm having some issues with the scenarios, I'm getting only the elevator #2 with the python file. It is also less clear in the Javascript file which elevator has been picked, although we can deduce it with the line printed for the requestFloor function.

Except for these, the code is still pretty good and you seem to understand well what you did. Make sure to check the mentionned problem just so you don't repeat them this week and should be good. Keep up the good work.

**Comment by EmmanuellaD** [comment]
Do you need me to fix it? I can do that over the week end
